# Add your additional Hyprland configurations here
env = EDITOR,zeditor --wait
cursor {
    no_hardware_cursors = true
}

bind = SUPER, SPACE, exec, ~/.config/hypr/scripts/launcher.sh
bind = CTRL, semicolon, exec, $SCRIPTS/ml4w-cliphist
bind = $mainMod, L, exec, hyprlock

# Lid closed
bindl = , switch:on:Lid Switch, exec, ~/.config/hypr/scripts/lid.sh close
# Lid opened
bindl = , switch:off:Lid Switch, exec, ~/.config/hypr/scripts/lid.sh open

# 1Password
exec-once = 1password --silent
